[functions]

  [functions.emails]
  included_files = [
    "./emails/**"
  ]

[context]

  [context.production]

    [context.production.functions]

      [context.production.functions.emails]
      included_files = [
        "./emails/**"
      ]

  [context.main]

    [context.main.functions]

      [context.main.functions.emails]
      included_files = [
        "./emails/**"
      ]

[build]
  functions = "functions/"

[[plugins]]
  package = "netlify-plugin-form-submissions"

[form-processing]
  mailchimpListId = "your-list-id"  # Opcional, puedes usar Mailchimp u otro proveedor
  backend = "functions"
  notification_emails = ["tu-correo@ejemplo.com"]  # Reemplaza con tu dirección de correo electrónico
